### ISSUE TITLE
Please rename default branch to main

### ISSUE THREAD

**Issue by JayamalHettiarachchi** [typefi/run-script-examples#6]
This is related to https://github.com/typefi/devops/issues/2.

**Comment by JayamalHettiarachchi** [comment]
Hi @dinesh-amarasekara,
Can you please grant admin access to get this done?
Thanks.

**Comment by dinesh-amarasekara** [comment]
Hi @JayamalHettiarachchi,

OK. Granted admin rights. Please check.

Dinesh.

**Comment by JayamalHettiarachchi** [comment]
Thank you @dinesh-amarasekara

**Comment by JayamalHettiarachchi** [comment]
Done
